"""Ports implemented by exchange, storage, and notification adapters."""

from __future__ import annotations

from decimal import Decimal
from typing import Any, Iterable, Mapping, Optional, Protocol, Sequence

from .models import (AccountSnapshot, Candle, ClosedTrade, Instrument, OrderFill, Position, Signal,
                     StrategyEvent, TradePlan, TradeSettlement)


class MarketDataPort(Protocol):
    def instruments(self) -> Mapping[str, Instrument]: ...
    def market_summaries(self) -> Sequence[Mapping[str, Any]]: ...
    def candles(self, symbol: str, interval: str, limit: int) -> Sequence[Candle]: ...
    def live_candles(self, symbol: str, interval: str, limit: int) -> Sequence[Candle]: ...
    def mark_price(self, symbol: str) -> Decimal: ...
    def book(self, symbol: str) -> Mapping[str, Decimal]: ...
    def futures_flow(self, symbol: str) -> Mapping[str, Decimal]: ...


class ExchangePort(Protocol):
    def account(self) -> AccountSnapshot: ...
    def set_leverage(self, symbol: str, leverage: int) -> None: ...
    def enter(self, plan: TradePlan, slippage: Decimal) -> OrderFill: ...
    def reduce(self, position: Position, quantity: Decimal, slippage: Decimal) -> OrderFill: ...
    def emergency_close(self, position: Position) -> OrderFill: ...
    def replace_stop(self, position: Position, stop_price: Decimal) -> str: ...
    def cancel_symbol_orders(self, symbol: str) -> None: ...
    def position_amount(self, symbol: str) -> Decimal: ...
    def open_position_symbols(self) -> Sequence[str]: ...
    def settlement(self, position: Position, end_ms: int) -> Optional[TradeSettlement]: ...


class TradeStorePort(Protocol):
    def load_open_positions(self, strategy: str, mode: str) -> Sequence[Position]: ...
    def load_last_open_times(self, strategy: str, mode: str) -> Mapping[str, int]: ...
    def save_signal(self, signal: Signal, mode: str) -> None: ...
    def save_open(self, position: Position, mode: str, score: Decimal, reason: str,
                  entry_context: str = "normal",
                  metrics: Optional[Mapping[str, Any]] = None) -> None: ...
    def save_position(self, position: Position) -> None: ...
    def save_close(self, position: Position, exit_price: Decimal, net_pnl: Decimal, reason: str) -> None: ...
    def daily_net_pnl(self, strategy: str, mode: str, start_ms: int, end_ms: int) -> Decimal: ...
    def recent_fast_stop_candidates(
        self, source_strategies: Sequence[str], start_ms: int, end_ms: int,
        max_duration_seconds: int,
    ) -> Sequence[ClosedTrade]: ...
    def last_closed_trade(
        self, strategy: str, mode: str, symbol: str,
    ) -> Optional[ClosedTrade]: ...
    def count_stop_losses(
        self, strategy: str, mode: str, symbol: str, side: Side,
        start_ms: int, end_ms: int,
    ) -> int: ...
    def has_losing_trade(
        self, strategy: str, mode: str, symbol: str, start_ms: int, end_ms: int,
    ) -> bool: ...
    def event_seen(self, event_id: str, strategy: str, mode: str) -> bool: ...
    def save_event(self, event: StrategyEvent, status: str, mode: str, version: str) -> None: ...
    def close(self) -> None: ...


class NotifierPort(Protocol):
    def send(self, message: str) -> None: ...


class StrategyPort(Protocol):
    name: str
    version: str
    interval: str
    candle_limit: int

    def select_universe(self, market: MarketDataPort) -> Sequence[str]: ...
    def evaluate(self, symbol: str, candles: Sequence[Candle], mark: Decimal) -> Optional[Signal]: ...
    def manage(self, position: Position, candles: Sequence[Candle], mark: Decimal) -> Iterable[Any]: ...


class EventStrategyPort(Protocol):
    name: str
    version: str
    interval: str
    candle_limit: int

    def poll_events(self, market: MarketDataPort) -> Sequence[StrategyEvent]: ...
    def manage(self, position: Position, candles: Sequence[Candle], mark: Decimal) -> Iterable[Any]: ...
